# Generated by Django 4.2.7 on 2025-12-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Расположение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото')),
                ('equipments', models.ManyToManyField(blank=True, to='rooms.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема встречи')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('attendees', models.PositiveIntegerField(default=1, verbose_name='Участников')),
                ('status', models.CharField(choices=[('P', 'Ожидает'), ('A', 'Подтверждено'), ('R', 'Отменено')], default='P', max_length=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('equipment', models.ManyToManyField(blank=True, to='rooms.equipment', verbose_name='Доп. оборудование')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-start'],
            },
        ),
    ]
